// Public Suffix List lookups (https://publicsuffix.org/list/).
//
// The rule table is bundled in public-suffix-list.js and regenerated by
// scripts/update-public-suffix-list.mjs, so nothing here touches the network.

import { PUBLIC_SUFFIX_RULES } from "./public-suffix-list.js";

let tables = null;

function buildTables() {
  const normal = new Set();
  const wildcard = new Set();
  const exception = new Set();

  for (const rule of PUBLIC_SUFFIX_RULES.split("\n")) {
    if (!rule) continue;

    if (rule.startsWith("!")) {
      exception.add(rule.slice(1));
    } else if (rule.startsWith("*.")) {
      wildcard.add(rule.slice(2));
    } else {
      normal.add(rule);
    }
  }

  return { normal, wildcard, exception };
}

function suffixTables() {
  if (!tables) tables = buildTables();
  return tables;
}

export function isIpAddress(host) {
  if (/^\d{1,3}(\.\d{1,3}){3}$/.test(host)) {
    return host.split(".").every(part => Number(part) <= 255);
  }
  // Bracketed or bare IPv6, plus anything else carrying a colon.
  return host.includes(":");
}

// Number of trailing labels that form the public suffix of `host`, following
// the PSL algorithm: exception rules win, then the longest matching rule, and
// an unlisted TLD falls back to the implicit "*" rule.
export function publicSuffixLength(host) {
  const { normal, wildcard, exception } = suffixTables();
  const labels = host.split(".");

  for (let i = 0; i < labels.length; i++) {
    const candidate = labels.slice(i).join(".");
    const remaining = labels.length - i;

    // "!city.kawasaki.jp" means city.kawasaki.jp is registrable, so the public
    // suffix is the rule without its leftmost label.
    if (exception.has(candidate)) return remaining - 1;
    if (normal.has(candidate)) return remaining;
    if (i + 1 < labels.length && wildcard.has(labels.slice(i + 1).join("."))) return remaining;
  }

  return 1;
}

export function publicSuffixOf(host) {
  const labels = String(host || "").split(".");
  return labels.slice(labels.length - publicSuffixLength(host)).join(".");
}

// Registrable domain: the public suffix plus one label. Hosts that are
// themselves a public suffix (or shorter) are returned unchanged — reducing
// them further would hand RouterOS something like "co.uk".
export function registrableDomain(host) {
  const name = String(host || "");
  if (!name) return "";
  if (isIpAddress(name)) return name;

  const labels = name.split(".");
  if (labels.length < 2) return name;

  const suffixLength = publicSuffixLength(name);
  if (labels.length <= suffixLength) return name;

  return labels.slice(labels.length - suffixLength - 1).join(".");
}
